# Exercise NumPy

In [1]:
import numpy as np

In [2]:
my_array = np.array([1,10,-5,20,77])

In [3]:
my_array

array([ 1, 10, -5, 20, 77])

In [5]:
print(f"The mean is {my_array.mean()}")
print(f"The mean is {my_array.std()}")

The mean is 20.6
The mean is 29.43874997346185


In [9]:
print(f"Multiplication by 2:{my_array*2}")

Multiplication by 2:[  2  20 -10  40 154]


In [11]:
my_arr_4x3 = np.array([[1,2,3], [4,5,6],[7,8,9],[10,11,12]])
my_arr_4x3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
my_arr_4x3 * 4.5

array([[ 4.5,  9. , 13.5],
       [18. , 22.5, 27. ],
       [31.5, 36. , 40.5],
       [45. , 49.5, 54. ]])

In [17]:
my_arr_4x3_inverted = my_arr_4x3.T
my_arr_4x3_inverted

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [20]:
print(f"Inverted Matrix: \n {my_arr_4x3.T}")

Inverted Matrix: 
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [21]:
# how many elements are there in the matrix?

In [22]:
print(f"Elements in this matrix: \n {my_arr_4x3.size}")

Elements in this matrix: 
 12


In [23]:
print(f"Shape of this matrix: \n {my_arr_4x3.shape}")

Shape of this matrix: 
 (4, 3)


In [30]:
random_integers = np.random.randint(100,200, 20)
random_integers

array([135, 175, 138, 139, 108, 179, 194, 119, 128, 150, 157, 181, 159,
       114, 178, 125, 115, 182, 114, 136])

In [33]:
100%2 # when the module is zero, then the integer is even 

0

In [35]:
random_integers % 2 

array([1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0])

In [36]:
random_integers % 2  == 0 # this is the condition and has to be parsed to the main arrays

array([False, False,  True, False,  True, False,  True, False,  True,
        True, False, False, False,  True,  True, False, False,  True,
        True,  True])

In [39]:
even_numbers = random_integers[random_integers % 2  == 0]

In [40]:
even_numbers

array([138, 108, 194, 128, 150, 114, 178, 182, 114, 136])

In [44]:
sliced_array = even_numbers[2:8]
sliced_array

array([194, 128, 150, 114, 178, 182])

In [53]:
arr1=np.random.randint(0,10,4)
arr2=np.random.randint(0,10,4)

print(f"The two arrays are: \n{arr1}\n{arr2}")

The two arrays are: 
[6 7 6 4]
[8 8 4 3]


In [55]:
print(f"The sum of the two arrays is: \n{arr1+arr2}")
print(f"The multiplication of the two arrays is: \n{arr1*arr2}")

The sum of the two arrays is: 
[14 15 10  7]
The multiplication of the two arrays is: 
[48 56 24 12]


In [56]:
np.dot(arr1,arr2)

np.int64(140)