In [1]:
import numpy as np

In [13]:
dataset = np.genfromtxt('data.csv', delimiter=';')

In [14]:
dataset 

array([[ 76.,  52.,  56.,  77.,  20.,  65.,  38.,  36.,  17.,  11.],
       [  6.,  26.,  78.,  26.,  63.,  69.,  55.,   6.,   3.,  55.],
       [ 98.,   9.,  36.,  61.,  23.,  17.,  32.,  12.,  93.,  85.],
       [ 66.,  75.,  86.,   4.,   3.,  10.,  51.,  48.,  20.,  28.],
       [ 82.,  31.,  20.,  15.,  93.,   3.,  64.,  15.,  31.,  59.],
       [ 79.,  78.,  44.,  13.,  49.,  36.,  61.,  36.,  49.,  89.],
       [ 85.,  21.,  39.,  24.,  69.,  32.,  46.,  10.,  97.,   3.],
       [ 74.,  71.,  78.,  50.,  87.,  16.,  10.,  74.,  32.,   8.],
       [ 60.,   9.,  84.,  89.,  37.,  90.,  49.,  95.,  43.,  24.],
       [ 25.,   5.,  42.,   1.,  18.,  28.,  86.,  75.,  27.,  94.],
       [ 33.,  15.,  94.,  64.,  49.,  92.,  99.,  28.,  51.,  76.],
       [  2.,  54.,  54.,  40.,  87.,  97.,  50.,  19.,  93.,  33.],
       [ 45.,  73.,  75.,   9.,  52.,  77.,  30.,  25.,   5.,  88.],
       [ 58.,  91.,  43.,  91.,  99.,  95., 100.,  48.,  13.,  47.],
       [ 57.,  52.,  17.,  54.,  4

In [15]:
sum(dataset)

array([1210., 1154., 1156., 1084., 1344., 1121., 1212., 1060., 1052.,
       1206.])

In [16]:
dataset.sum()

np.float64(11599.0)

In [17]:
column_index = 0 
column_data = dataset[:,column_index]
column_data

array([76.,  6., 98., 66., 82., 79., 85., 74., 60., 25., 33.,  2., 45.,
       58., 57., 94., 33., 12., 49., 37., 37., 10.,  7., 85.])